# RocketMQ Broker 配置文件
# 允许自动创建 Topic
autoCreateTopicEnable=true

# Broker 名称
brokerName=broker-a

# Broker 所属集群名称
brokerClusterName=DefaultCluster

# Broker 地址（0.0.0.0 表示自动获取）
brokerIP1=127.0.0.1

# 删除文件时间点，默认凌晨 4 点
deleteWhen=04

# 文件保留时间，默认 48 小时
fileReservedTime=48

# broker 角色
brokerRole=ASYNC_MASTER

# 刷盘方式
flushDiskType=ASYNC_FLUSH

# 监听端口
listenPort=10911

# 是否允许 Slaver 读取
readSlavertFromSlave=false

# 消息存储路径
storePathRootDir=/home/rocketmq/store

# 消息 CommitLog 存储路径
storePathCommitLog=/home/rocketmq/store/commitlog

# 消息消费队列存储路径
storePathConsumeQueue=/home/rocketmq/store/consumequeue

# 消息索引存储路径
storePathIndex=/home/rocketmq/store/index

# 延迟消息队列数
delayTimeLevel=5
