spring:
  application:
    name: recharge-statistics-service

rocketmq:
  name-server: localhost:9876
  producer:
    group: statistics-producer-group
    send-message-timeout: 3000
  consumer:
    group: statistics-group

server:
  port: 8083
